version: "2"

run:
  timeout: 5m
  tests: true

formatters:
  enable:
    - gofumpt
    - goimports
    - gci
    - golines
  settings:
    gofumpt:
      module-path: github.com/andyballingall/json-schema-manager
    goimports:
      # A list of prefixes, which, if set, checks import paths
      # with the given prefixes are grouped after 3rd-party packages.
      # Default: []
      local-prefixes:
        - github.com/andyballingall/json-schema-manager
    golines:
      max-len: 120

linters:
  enable:
    # Basics
    - errcheck
    - staticcheck
    - unused
    - ineffassign

    # Formatting & Style
    - revive
    - misspell
    - lll
    - whitespace
    - goconst

    # Complexity & Quality
    - gocritic
    - unconvert
    - prealloc
    - nakedret
    - dogsled
    - errorlint
    - nilerr
    - copyloopvar
    - unparam

    # Security & Resources
    - gosec
    - bodyclose
    - noctx

    # Testing & Maintenance
    - testifylint
    - thelper
    - nolintlint

    # NEW: Quality & Safety
    - tagliatelle
    - errname
    - forcetypeassert
    - makezero
    - gocognit
    - godot
    - paralleltest
    - tparallel
    - usestdlibvars
    - dupl
    - wastedassign
  settings:
    govet:
      # ENABLE-ALL ensures standard checks (printf, atomic, etc.) are active.
      enable-all: true
      disable:
        - fieldalignment

    gocyclo:
      min-complexity: 15

    misspell:
      locale: UK

    lll:
      line-length: 120

    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
        - experimental
        - opinionated
      disabled-checks:
        - dupImport
        - whyNoLint
        - wrapperFunc

    nolintlint:
      allow-unused: false
      require-explanation: true
      require-specific: true

    testifylint:
      enable-all: true

    goconst:
      min-len: 3
      min-occurrences: 3

    tagliatelle:
      case:
        rules:
          json: camel
          yaml: camel

    gocognit:
      min-complexity: 10

    godot:
      scope: declarations
      capital: true
