version: "2"

run:
  timeout: 5m
  tests: true

formatters:
  enable:
    - gofumpt
    - goimports
    - gci
    - golines
  settings:
    gofumpt:
      module-path: github.com/bitshepherds/json-schema-manager
    goimports:
      local-prefixes:
        - github.com/bitshepherds/json-schema-manager
    golines:
      max-len: 120
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/bitshepherds/json-schema-manager)

linters:
  enable:
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - revive
    - misspell
    - lll
    - whitespace
    - goconst
    - gocyclo
    - gocritic
    - unconvert
    - prealloc
    - nakedret
    - dogsled
    - errorlint
    - nilerr
    - copyloopvar
    - unparam
    - gosec
    - bodyclose
    - noctx
    - testifylint
    - thelper
    - nolintlint
    - tagliatelle
    - errname
    - forcetypeassert
    - makezero
    - gocognit
    - godot
    - paralleltest
    - tparallel
    - usestdlibvars
    - dupl
    - wastedassign
  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment
    gocyclo:
      min-complexity: 15
    misspell:
      locale: UK
    lll:
      line-length: 120
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
        - experimental
        - opinionated
      disabled-checks:
        - dupImport
        - whyNoLint
        - wrapperFunc
    nolintlint:
      allow-unused: false
      require-explanation: true
      require-specific: true
    testifylint:
      enable-all: true
    goconst:
      min-len: 3
      min-occurrences: 3
    tagliatelle:
      case:
        rules:
          json: camel
          yaml: camel
    gocognit:
      min-complexity: 15
    godot:
      scope: declarations
      capital: true
  exclusions:
    rules:
      - path: '(.+)_test\.go'
        linters:
          - gocyclo
          - gocognit
          - gosec
          - gocritic
      - path: "scripts/(.+)"
        linters:
          - gosec
